### ISSUE TITLE
metrics-logstash-node.rb not working with Logstash 7.3.0

### ISSUE THREAD

**Issue by boutetnico** [sensu-plugins/sensu-plugins-logstash#41]
After upgrading from Logstash 7.2.0 to 7.3.0 I noticed `metrics-logstash-node.rb` started returning an error:

```
$ ruby /opt/sensu/embedded/bin/metrics-logstash-node.rb
Check failed to run: undefined method `each' for nil:NilClass, ["/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-logstash-2.1.0/bin/metrics-logstash-node.rb:118:in `run'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugin-1.4.7/lib/sensu-plugin/cli.rb:58:in `block in <class:CLI>'"]
```

After doing some research, it seems a new `pipeline` key was introduced in the http response. This confuses `metrics-logstash-node.rb` because this script is checking the existence of this key to determine logstash version as shown below.

```ruby
# logstash < 6.0
if node.key?('pipeline')

# Logic handling logstash < 6.0 metrics

# logstash >= 6.0
    elsif node.key?('pipelines')

# Logic handling logstash >= 6.0 metrics
```

A simple fix I found is to add the following check:

```ruby
# logstash < 6.0
if node.key?('pipeline') and node['pipeline'].key?('workers')
```

I'll provide a PR and will be happy to receive feedback on this solution.
